### ISSUE TITLE
error on vim 7.4 which is installed in  centos7 

### ISSUE THREAD

**Issue by leoatchina** [brglng/vim-sidebar-manager#2]
第   28 行:
E15: 无效的表达式: > bufname(winbufnr(nr)) =~ '_Mundo_'}, 'open': 'MundoShow', 'close': 'MundoHide' }
E15: 无效的表达式: { 'position': 'left', 'check_win': {nr -> bufname(winbufnr(nr)) =~ '_Mundo_'}, 'open': 'MundoShow', 'close': 'MundoHide' }

It looked like the error is caused in 
` {nr ->  getwinvar(nr, '&filetype') ==# 'undotree'}` , maybe  `->`  is not allowed in vim7.4

**Comment by leoatchina** [comment]
I have change undo_tool to undotree, the same error happened

**Comment by brglng** [comment]
@leoatchina Vim 7.4 does not support lambda expression. Maybe you have to use a named function.

**Comment by leoatchina** [comment]
emmmm,  one question 
Is `{nr -> bufname(winbufnr(nr)) =~ '__Tagbar__'}`    a lamda function  to return the winid ?
so I should define a function to return the **winid** of the the sidebar I need ? And attach the function to `check_win ` ?

**Comment by brglng** [comment]
@leoatchina No, you should define a function who accepts a single parameter `nr`, which is the **window number**, not **winid**, and return a number (boolean) to indicate whether or not the window corresponding to this `winnr` is the sidebar window.

**Comment by brglng** [comment]
Closed for no action.
